# Build and the Agda code and render to HTML.
# Prerequisites: agda and the standard-library are installed.

agda=agda

.PHONY: default
default: html

.PHONY: html
html:
	agda --html Main.agda

# EOF
