name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  AGDA_VERSION: '2.8.0'
  STDLIB_VERSION: '2.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Setup

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v4

      - name: Install Agda ${{ env.AGDA_VERSION }}
        id: setup-agda
        uses: agda/agda-setup-action@v1
        with:
          agda-version: ${{ env.AGDA_VERSION }}
          agda-stdlib-version: ${{ env.STDLIB_VERSION }}

      - name: Set up environment variables
        run: |
          echo "HOME = ${HOME}"
          echo "current directory = $(pwd)"
          agda --version
          pandoc --version
          tectonic --version
          echo "TECTONIC_VERSION=$(tectonic --version)"            >> "${GITHUB_ENV}"
          echo "TECTONIC_CACHE=$(tectonic -X show user-cache-dir)" >> "${GITHUB_ENV}"
        # This errors because pandoc --version does not emit a single line
        # echo "PANDOC_VERSION=$(pandoc --version)"                >> "${GITHUB_ENV}"

      # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
      - uses: actions/checkout@v6

      # Restore caches

      - name: Restore Tectonic cache
        uses: actions/cache/restore@v5
        id:   cache-tectonic
        env:
          key: tectonic-${{ env.TECTONIC_VERSION }}
        with:
          key:          ${{ env.key }}-${{ github.sha }}
          restore-keys: ${{ env.key }}-
          path:         ${{ env.TECTONIC_CACHE }}

      - name: Restore Agda cache
        uses: actions/cache/restore@v5
        id:   cache-agda
        env:
          AGDA_DIR: ${{ steps.setup-agda.outputs.agda-dir }}
        with:
          key: agda-${{ env.AGDA_VERSION }}-stdlib-${{ env.STDLIB_VERSION }}-commit-${{ github.sha }}
          restore-keys: agda-${{ env.AGDA_VERSION }}-stdlib-${{ env.STDLIB_VERSION }}-
          path: |
            ${{ env.SRC_DIR }}/_build
            ${{ env.AGDA_DIR }}/libraries.d

      # Build

      - name: Build
        run: make

      # Save caches

      - name: Save Tectonic cache
        uses: actions/cache/save@v5
        # Primary cache key is unique, so we can always save.
        if:   always()
        with:
          key:  ${{ steps.cache-tectonic.outputs.cache-primary-key }}
          path: ${{ env.TECTONIC_CACHE }}

      - name: Save Agda cache
        uses: actions/cache/save@v5
        # Primary cache key is unique, so we can always save.
        if:   always()
        env:
          AGDA_DIR: ${{ steps.setup-agda.outputs.agda-dir }}
        with:
          key: ${{ steps.cache-agda.outputs.cache-primary-key }}
          path: |
            ${{ env.SRC_DIR }}/_build
            ${{ env.AGDA_DIR }}/libraries.d

      - uses: actions/upload-pages-artifact@v5
        with:
          path: .

  # Deploy job

  deploy:
    if: github.ref == 'refs/heads/master'
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages:    write   # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to GitHub Pages
      id:   deployment
      uses: actions/deploy-pages@v5
